const ActionTypes = {
    PLAYER_CONNECTED: 'PLAYER_CONNECTED',
    PLAYER_SOLVE_TASK: 'PLAYER_SOLVE_TASK',
    PLAYER_GET_TASK: 'PLAYER_SOLVE_TASK',
    PLAYER_WIN: 'PLAYER_WIN',
    PLAYER_CLOSE_CONNECTION: 'PLAYER_CLOSE_CONNECTION',
    REMOVE_PLAYER: 'REMOVE_PLAYER',
};

export default ActionTypes;
